#name: Build and deploy action
#on: [push]
#jobs:
#  build_and_push:
#    runs-on: ubuntu-latest
#    steps:
#    - name: clone code
#      uses: actions/checkout@v2
#    - name: docker build
#      run: docker build -t rgazizulin/skygramm:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
#    - name: docker login
#      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#    - name: docker push
#      run: docker push rgazizulin/skygramm:$GITHUB_REF_NAME-$GITHUB_RUN_ID
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build_and_push
#    steps:
#      - name: clone code
#        uses: actions/checkout@v2
#      - name: render configs
#        run: |
#          mkdir skygramm
#          cat docker-compose-ci.yaml | envsubst > skygramm/docker-compose.yaml
#      - name: copy files to server
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          source: "skygramm/docker-compose.yaml"
#          target: "skygramm_app"
#          strip_components: 1
#      - name: deploy app
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.PASSWORD }}
#          script: |
#            cd skygramm_app
#            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose down
#            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d

